<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class GiangviensTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('giangviens')->insert([
            [
                'maGV' => 'GV01',
                'maNganh' => 'N01',
                'hoTen' => 'Nguyễn Minh P',
                'ngaySinh' => '1980-01-01',
                'gioiTinh' => 'M',
                'diaChi' => '123 Đường P',
                'email' => 'nguyenminhp@example.com',
                'tenDN' => 'nguyenminhp',
                'matKhau' => 'password',
                'soCCCD' => '123456789012',
                'hocHam' => 'Phó Giáo sư',
                'hocVi' => 'Tiến sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV02',
                'maNganh' => 'N02',
                'hoTen' => 'Trần Thanh Q',
                'ngaySinh' => '1981-02-02',
                'gioiTinh' => 'M',
                'diaChi' => '456 Đường Q',
                'email' => 'tranthanhq@example.com',
                'tenDN' => 'tranthanhq',
                'matKhau' => 'password',
                'soCCCD' => '234567890123',
                'hocHam' => 'Giáo sư',
                'hocVi' => 'Tiến sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV03',
                'maNganh' => 'N03',
                'hoTen' => 'Lê Ngọc R',
                'ngaySinh' => '1982-03-03',
                'gioiTinh' => 'F',
                'diaChi' => '789 Đường R',
                'email' => 'lengocr@example.com',
                'tenDN' => 'lengocr',
                'matKhau' => 'password',
                'soCCCD' => '345678901234',
                'hocHam' => 'Phó Giáo sư',
                'hocVi' => 'Tiến sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV04',
                'maNganh' => 'N04',
                'hoTen' => 'Phạm Văn S',
                'ngaySinh' => '1983-04-04',
                'gioiTinh' => 'M',
                'diaChi' => '123 Đường S',
                'email' => 'phamvans@example.com',
                'tenDN' => 'phamvans',
                'matKhau' => 'password',
                'soCCCD' => '456789012345',
                'hocHam' => 'Giáo sư',
                'hocVi' => 'Tiến sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV05',
                'maNganh' => 'N05',
                'hoTen' => 'Hoàng Thị T',
                'ngaySinh' => '1984-05-05',
                'gioiTinh' => 'F',
                'diaChi' => '234 Đường T',
                'email' => 'hoangthit@example.com',
                'tenDN' => 'hoangthit',
                'matKhau' => 'password',
                'soCCCD' => '567890123456',
                'hocHam' => 'Phó Giáo sư',
                'hocVi' => 'Thạc sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV06',
                'maNganh' => 'N06',
                'hoTen' => 'Vũ Văn U',
                'ngaySinh' => '1985-06-06',
                'gioiTinh' => 'M',
                'diaChi' => '567 Đường U',
                'email' => 'vuvanu@example.com',
                'tenDN' => 'vuvanu',
                'matKhau' => 'password',
                'soCCCD' => '678901234567',
                'hocHam' => 'Phó Giáo sư',
                'hocVi' => 'Tiến sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV07',
                'maNganh' => 'N07',
                'hoTen' => 'Bùi Thị V',
                'ngaySinh' => '1986-07-07',
                'gioiTinh' => 'F',
                'diaChi' => '890 Đường V',
                'email' => 'buithiv@example.com',
                'tenDN' => 'buithiv',
                'matKhau' => 'password',
                'soCCCD' => '789012345678',
                'hocHam' => 'Giáo sư',
                'hocVi' => 'Thạc sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV08',
                'maNganh' => 'N08',
                'hoTen' => 'Đỗ Văn X',
                'ngaySinh' => '1987-08-08',
                'gioiTinh' => 'M',
                'diaChi' => '321 Đường X',
                'email' => 'dovanx@example.com',
                'tenDN' => 'dovanx',
                'matKhau' => 'password',
                'soCCCD' => '890123456789',
                'hocHam' => 'Phó Giáo sư',
                'hocVi' => 'Tiến sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV09',
                'maNganh' => 'N09',
                'hoTen' => 'Phan Thị Y',
                'ngaySinh' => '1988-09-09',
                'gioiTinh' => 'F',
                'diaChi' => '654 Đường Y',
                'email' => 'phanthiy@example.com',
                'tenDN' => 'phanthiy',
                'matKhau' => 'password',
                'soCCCD' => '901234567890',
                'hocHam' => 'Giáo sư',
                'hocVi' => 'Thạc sĩ',
                'trangThai' => '1',
            ],
            [
                'maGV' => 'GV10',
                'maNganh' => 'N10',
                'hoTen' => 'Trịnh Văn Z',
                'ngaySinh' => '1989-10-10',
                'gioiTinh' => 'M',
                'diaChi' => '987 Đường Z',
                'email' => 'trinhvanz@example.com',
                'tenDN' => 'trinhvanz',
                'matKhau' => 'password',
                'soCCCD' => '012345678901',
                'hocHam' => 'Phó Giáo sư',
                'hocVi' => 'Tiến sĩ',
                'trangThai' => '1',
            ],
        ]);
    }
}
